[2024-05-30T02:43:49.997+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_field scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2024-05-30T02:43:50.009+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_field scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2024-05-30T02:43:50.009+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-30T02:43:50.010+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-30T02:43:50.010+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-30T02:43:50.029+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): transform_field> on 2024-05-29 00:00:00+00:00
[2024-05-30T02:43:50.034+0000] {standard_task_runner.py:55} INFO - Started process 130 to run task
[2024-05-30T02:43:50.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'transform_field', 'scheduled__2024-05-29T00:00:00+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpt309oe3x']
[2024-05-30T02:43:50.038+0000] {standard_task_runner.py:83} INFO - Job 381: Subtask transform_field
[2024-05-30T02:43:50.118+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.transform_field scheduled__2024-05-29T00:00:00+00:00 [running]> on host 731e27f62632
[2024-05-30T02:43:50.198+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=transform_field
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-29T00:00:00+00:00
[2024-05-30T02:43:50.200+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-30T02:43:50.200+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/data_transform/transform_field.py']
[2024-05-30T02:43:50.210+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T02:43:50.347+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-30T02:43:50.348+0000] {subprocess.py:93} INFO -   File "/opt/***/data_transform/transform_field.py", line 19, in <module>
[2024-05-30T02:43:50.348+0000] {subprocess.py:93} INFO -     data = json.load(file)
[2024-05-30T02:43:50.349+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
[2024-05-30T02:43:50.349+0000] {subprocess.py:93} INFO -     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
[2024-05-30T02:43:50.350+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
[2024-05-30T02:43:50.350+0000] {subprocess.py:93} INFO -     return _default_decoder.decode(s)
[2024-05-30T02:43:50.350+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
[2024-05-30T02:43:50.351+0000] {subprocess.py:93} INFO -     raise JSONDecodeError("Extra data", s, end)
[2024-05-30T02:43:50.351+0000] {subprocess.py:93} INFO - json.decoder.JSONDecodeError: Extra data: line 46 column 2 (char 10922)
[2024-05-30T02:43:50.352+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T02:43:50.365+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T02:43:50.370+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=transform_field, execution_date=20240529T000000, start_date=20240530T024349, end_date=20240530T024350
[2024-05-30T02:43:50.384+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 381 for task transform_field (Bash command failed. The command returned a non-zero exit code 1.; 130)
[2024-05-30T02:43:50.412+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-30T02:43:50.443+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
