[2024-05-29T16:08:58.690+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_data manual__2024-05-29T16:08:57.090753+00:00 [queued]>
[2024-05-29T16:08:58.704+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_data manual__2024-05-29T16:08:57.090753+00:00 [queued]>
[2024-05-29T16:08:58.705+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T16:08:58.706+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T16:08:58.707+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T16:08:58.723+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_data> on 2024-05-29 16:08:57.090753+00:00
[2024-05-29T16:08:58.728+0000] {standard_task_runner.py:55} INFO - Started process 19150 to run task
[2024-05-29T16:08:58.730+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'load_data', 'manual__2024-05-29T16:08:57.090753+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpx0a0y5z9']
[2024-05-29T16:08:58.731+0000] {standard_task_runner.py:83} INFO - Job 126: Subtask load_data
[2024-05-29T16:08:58.800+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.load_data manual__2024-05-29T16:08:57.090753+00:00 [running]> on host 731e27f62632
[2024-05-29T16:08:58.861+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T16:08:57.090753+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T16:08:57.090753+00:00
[2024-05-29T16:08:58.863+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T16:08:58.864+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/load_mysql.py']
[2024-05-29T16:08:58.873+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T16:08:58.946+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/mysql_utils/load_mysql.py': [Errno 2] No such file or directory
[2024-05-29T16:08:58.949+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-29T16:08:58.959+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-29T16:08:58.963+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=load_data, execution_date=20240529T160857, start_date=20240529T160858, end_date=20240529T160858
[2024-05-29T16:08:58.976+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 126 for task load_data (Bash command failed. The command returned a non-zero exit code 2.; 19150)
[2024-05-29T16:08:58.986+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T16:08:59.001+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
