[2024-05-29T19:14:22.708+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_conference manual__2024-05-29T19:13:53.335173+00:00 [queued]>
[2024-05-29T19:14:22.717+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_conference manual__2024-05-29T19:13:53.335173+00:00 [queued]>
[2024-05-29T19:14:22.718+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T19:14:22.718+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T19:14:22.719+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T19:14:22.731+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_conference> on 2024-05-29 19:13:53.335173+00:00
[2024-05-29T19:14:22.735+0000] {standard_task_runner.py:55} INFO - Started process 42998 to run task
[2024-05-29T19:14:22.737+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'load_conference', 'manual__2024-05-29T19:13:53.335173+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpd8in83ke']
[2024-05-29T19:14:22.738+0000] {standard_task_runner.py:83} INFO - Job 352: Subtask load_conference
[2024-05-29T19:14:22.789+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.load_conference manual__2024-05-29T19:13:53.335173+00:00 [running]> on host 731e27f62632
[2024-05-29T19:14:22.838+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=load_conference
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T19:13:53.335173+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T19:13:53.335173+00:00
[2024-05-29T19:14:22.839+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T19:14:22.840+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/load_conference.py']
[2024-05-29T19:14:22.847+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T19:14:23.070+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-29T19:14:23.071+0000] {subprocess.py:93} INFO -   File "/opt/***/mysql_utils/load_conference.py", line 15, in <module>
[2024-05-29T19:14:23.071+0000] {subprocess.py:93} INFO -     cur.execute("INSERT INTO conferences(name, link, deadline, subformat, field_id, presenter_id, location_id, from_date, to_date, report_date) VALUES(%s, %s, STR_TO_DATE(%s,'%d/%m/%Y'), %s, %s, %s, %s, %s, %s, %s)", (row['name'], row['link'], row['deadline'], row['subformat'], row['field_id'], row['presenter_id'], row['location_id'], row['from_date'], row['to_date'], row['report_date']))
[2024-05-29T19:14:23.071+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 151, in execute
[2024-05-29T19:14:23.071+0000] {subprocess.py:93} INFO -     query = self.mogrify(query, args)
[2024-05-29T19:14:23.072+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 129, in mogrify
[2024-05-29T19:14:23.072+0000] {subprocess.py:93} INFO -     query = query % self._escape_args(args, conn)
[2024-05-29T19:14:23.072+0000] {subprocess.py:93} INFO - TypeError: %d format: a number is required, not str
[2024-05-29T19:14:23.076+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-29T19:14:23.084+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-29T19:14:23.087+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=load_conference, execution_date=20240529T191353, start_date=20240529T191422, end_date=20240529T191423
[2024-05-29T19:14:23.097+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 352 for task load_conference (Bash command failed. The command returned a non-zero exit code 1.; 42998)
[2024-05-29T19:14:23.112+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T19:14:23.129+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
