[2024-05-29T18:57:23.760+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_conference manual__2024-05-29T18:56:48.880889+00:00 [queued]>
[2024-05-29T18:57:23.769+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_conference manual__2024-05-29T18:56:48.880889+00:00 [queued]>
[2024-05-29T18:57:23.770+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T18:57:23.770+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T18:57:23.770+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T18:57:23.784+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_conference> on 2024-05-29 18:56:48.880889+00:00
[2024-05-29T18:57:23.788+0000] {standard_task_runner.py:55} INFO - Started process 40781 to run task
[2024-05-29T18:57:23.791+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'load_conference', 'manual__2024-05-29T18:56:48.880889+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpw3etiv9j']
[2024-05-29T18:57:23.791+0000] {standard_task_runner.py:83} INFO - Job 321: Subtask load_conference
[2024-05-29T18:57:23.846+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.load_conference manual__2024-05-29T18:56:48.880889+00:00 [running]> on host 731e27f62632
[2024-05-29T18:57:23.987+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=load_conference
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T18:56:48.880889+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T18:56:48.880889+00:00
[2024-05-29T18:57:23.996+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T18:57:24.005+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/load_conference.py']
[2024-05-29T18:57:24.027+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T18:57:24.266+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-29T18:57:24.266+0000] {subprocess.py:93} INFO -   File "/opt/***/mysql_utils/load_conference.py", line 12, in <module>
[2024-05-29T18:57:24.267+0000] {subprocess.py:93} INFO -     with open('/opt/***/data_stage_2/conference.json', 'r') as json_file:
[2024-05-29T18:57:24.267+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/data_stage_2/conference.json'
[2024-05-29T18:57:24.274+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-29T18:57:24.285+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-29T18:57:24.289+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=load_conference, execution_date=20240529T185648, start_date=20240529T185723, end_date=20240529T185724
[2024-05-29T18:57:24.308+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 321 for task load_conference (Bash command failed. The command returned a non-zero exit code 1.; 40781)
[2024-05-29T18:57:24.328+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T18:57:24.351+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
