[2024-05-29T16:01:53.926+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_data manual__2024-05-29T16:01:52.799526+00:00 [queued]>
[2024-05-29T16:01:53.933+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_data manual__2024-05-29T16:01:52.799526+00:00 [queued]>
[2024-05-29T16:01:53.934+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T16:01:53.934+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T16:01:53.935+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T16:01:53.945+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_data> on 2024-05-29 16:01:52.799526+00:00
[2024-05-29T16:01:53.949+0000] {standard_task_runner.py:55} INFO - Started process 18217 to run task
[2024-05-29T16:01:53.952+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'load_data', 'manual__2024-05-29T16:01:52.799526+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpwvxr5lnk']
[2024-05-29T16:01:53.952+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask load_data
[2024-05-29T16:01:54.003+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.load_data manual__2024-05-29T16:01:52.799526+00:00 [running]> on host 731e27f62632
[2024-05-29T16:01:54.075+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T16:01:52.799526+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T16:01:52.799526+00:00
[2024-05-29T16:01:54.077+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T16:01:54.078+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/load_mysql.py']
[2024-05-29T16:01:54.086+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T16:01:54.159+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/mysql_utils/load_mysql.py': [Errno 2] No such file or directory
[2024-05-29T16:01:54.162+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-29T16:01:54.170+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-29T16:01:54.174+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=load_data, execution_date=20240529T160152, start_date=20240529T160153, end_date=20240529T160154
[2024-05-29T16:01:54.184+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 113 for task load_data (Bash command failed. The command returned a non-zero exit code 2.; 18217)
[2024-05-29T16:01:54.204+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T16:01:54.219+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
