[2024-05-31T09:04:55.158+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T09:04:55.165+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T09:04:55.166+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T09:04:55.167+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-31T09:04:55.167+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T09:04:55.178+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): clean_data> on 2024-05-30 00:00:00+00:00
[2024-05-31T09:04:55.183+0000] {standard_task_runner.py:55} INFO - Started process 94 to run task
[2024-05-31T09:04:55.185+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'clean_data', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpfp2o4t43']
[2024-05-31T09:04:55.185+0000] {standard_task_runner.py:83} INFO - Job 398: Subtask clean_data
[2024-05-31T09:04:55.231+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [running]> on host 731e27f62632
[2024-05-31T09:04:55.289+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-30T00:00:00+00:00
[2024-05-31T09:04:55.291+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-31T09:04:55.292+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/dags/clean_all.py']
[2024-05-31T09:04:55.300+0000] {subprocess.py:86} INFO - Output:
[2024-05-31T09:04:55.523+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-31T09:04:55.541+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=conference_dag, task_id=clean_data, execution_date=20240530T000000, start_date=20240531T090455, end_date=20240531T090455
[2024-05-31T09:04:55.558+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-05-31T09:04:55.581+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T10:52:52.158+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T10:52:52.166+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T10:52:52.166+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T10:52:52.166+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-31T10:52:52.167+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-31T10:52:52.178+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): clean_data> on 2024-05-30 00:00:00+00:00
[2024-05-31T10:52:52.182+0000] {standard_task_runner.py:55} INFO - Started process 599 to run task
[2024-05-31T10:52:52.184+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'clean_data', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpv54a8_h7']
[2024-05-31T10:52:52.184+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask clean_data
[2024-05-31T10:52:52.233+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.clean_data scheduled__2024-05-30T00:00:00+00:00 [running]> on host 312e62f5d623
[2024-05-31T10:52:52.290+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-30T00:00:00+00:00
[2024-05-31T10:52:52.291+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-31T10:52:52.292+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/dags/clean_all.py']
[2024-05-31T10:52:52.299+0000] {subprocess.py:86} INFO - Output:
[2024-05-31T10:52:52.477+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-31T10:52:52.478+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clean_all.py", line 16, in <module>
[2024-05-31T10:52:52.478+0000] {subprocess.py:93} INFO -     cur.execute('DELETE FROM ***.conferences;')
[2024-05-31T10:52:52.478+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 153, in execute
[2024-05-31T10:52:52.478+0000] {subprocess.py:93} INFO -     result = self._query(query)
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 322, in _query
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -     conn.query(q)
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/connections.py", line 563, in query
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/connections.py", line 825, in _read_query_result
[2024-05-31T10:52:52.479+0000] {subprocess.py:93} INFO -     result.read()
[2024-05-31T10:52:52.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/connections.py", line 1199, in read
[2024-05-31T10:52:52.480+0000] {subprocess.py:93} INFO -     first_packet = self.connection._read_packet()
[2024-05-31T10:52:52.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_packet
[2024-05-31T10:52:52.480+0000] {subprocess.py:93} INFO -     packet.raise_for_error()
[2024-05-31T10:52:52.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/protocol.py", line 219, in raise_for_error
[2024-05-31T10:52:52.481+0000] {subprocess.py:93} INFO -     err.raise_mysql_exception(self._data)
[2024-05-31T10:52:52.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
[2024-05-31T10:52:52.481+0000] {subprocess.py:93} INFO -     raise errorclass(errno, errval)
[2024-05-31T10:52:52.481+0000] {subprocess.py:93} INFO - pymysql.err.ProgrammingError: (1146, "Table '***.conferences' doesn't exist")
[2024-05-31T10:52:52.485+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-31T10:52:52.493+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-31T10:52:52.495+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=clean_data, execution_date=20240530T000000, start_date=20240531T105252, end_date=20240531T105252
[2024-05-31T10:52:52.508+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task clean_data (Bash command failed. The command returned a non-zero exit code 1.; 599)
[2024-05-31T10:52:52.516+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-31T10:52:52.538+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
