[2024-05-29T13:51:58.383+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_data manual__2024-05-29T13:51:51.111128+00:00 [queued]>
[2024-05-29T13:51:58.391+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_data manual__2024-05-29T13:51:51.111128+00:00 [queued]>
[2024-05-29T13:51:58.392+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T13:51:58.393+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T13:51:58.393+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T13:51:58.404+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): transform_data> on 2024-05-29 13:51:51.111128+00:00
[2024-05-29T13:51:58.409+0000] {standard_task_runner.py:55} INFO - Started process 2044 to run task
[2024-05-29T13:51:58.411+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'transform_data', 'manual__2024-05-29T13:51:51.111128+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpfu80z2so']
[2024-05-29T13:51:58.411+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask transform_data
[2024-05-29T13:51:58.462+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.transform_data manual__2024-05-29T13:51:51.111128+00:00 [running]> on host 731e27f62632
[2024-05-29T13:51:58.512+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T13:51:51.111128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T13:51:51.111128+00:00
[2024-05-29T13:51:58.513+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T13:51:58.514+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/data_transform/transform.py']
[2024-05-29T13:51:58.521+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T13:51:58.631+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-29T13:51:58.632+0000] {subprocess.py:93} INFO -   File "/opt/***/data_transform/transform.py", line 124, in <module>
[2024-05-29T13:51:58.633+0000] {subprocess.py:93} INFO -     raise FileNotFoundError(f"Tệp {input_file} không tồn tại. Vui lòng kiểm tra đường dẫn.")
[2024-05-29T13:51:58.633+0000] {subprocess.py:93} INFO - FileNotFoundError: Tệp ../data_stage_1/stage_1.json không tồn tại. Vui lòng kiểm tra đường dẫn.
[2024-05-29T13:51:58.634+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-29T13:51:58.641+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-29T13:51:58.644+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=transform_data, execution_date=20240529T135151, start_date=20240529T135158, end_date=20240529T135158
[2024-05-29T13:51:58.654+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 104 for task transform_data (Bash command failed. The command returned a non-zero exit code 1.; 2044)
[2024-05-29T13:51:58.665+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T13:51:58.682+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
