[2024-05-29T19:33:23.181+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_conference manual__2024-05-29T19:32:58.185880+00:00 [queued]>
[2024-05-29T19:33:23.189+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.transform_conference manual__2024-05-29T19:32:58.185880+00:00 [queued]>
[2024-05-29T19:33:23.189+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T19:33:23.190+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T19:33:23.191+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T19:33:23.200+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): transform_conference> on 2024-05-29 19:32:58.185880+00:00
[2024-05-29T19:33:23.205+0000] {standard_task_runner.py:55} INFO - Started process 45427 to run task
[2024-05-29T19:33:23.207+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'transform_conference', 'manual__2024-05-29T19:32:58.185880+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmp90yzhck5']
[2024-05-29T19:33:23.207+0000] {standard_task_runner.py:83} INFO - Job 366: Subtask transform_conference
[2024-05-29T19:33:23.254+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.transform_conference manual__2024-05-29T19:32:58.185880+00:00 [running]> on host 731e27f62632
[2024-05-29T19:33:23.303+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=transform_conference
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T19:32:58.185880+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T19:32:58.185880+00:00
[2024-05-29T19:33:23.305+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T19:33:23.305+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/data_transform/transform_conference.py']
[2024-05-29T19:33:23.313+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T19:33:23.453+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-05-29T19:33:23.453+0000] {subprocess.py:93} INFO -   File "/opt/***/data_transform/transform_conference.py", line 124, in <module>
[2024-05-29T19:33:23.454+0000] {subprocess.py:93} INFO -     format_deadline(conference)
[2024-05-29T19:33:23.454+0000] {subprocess.py:93} INFO -   File "/opt/***/data_transform/transform_conference.py", line 63, in format_deadline
[2024-05-29T19:33:23.455+0000] {subprocess.py:93} INFO -     deadline = datetime.now().strftime("%d/%m/%Y")
[2024-05-29T19:33:23.455+0000] {subprocess.py:93} INFO - AttributeError: module 'datetime' has no attribute 'now'
[2024-05-29T19:33:23.456+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-29T19:33:23.464+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-29T19:33:23.467+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=conference_dag, task_id=transform_conference, execution_date=20240529T193258, start_date=20240529T193323, end_date=20240529T193323
[2024-05-29T19:33:23.478+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 366 for task transform_conference (Bash command failed. The command returned a non-zero exit code 1.; 45427)
[2024-05-29T19:33:23.500+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-29T19:33:23.519+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
